name: Automatic Testing

run-name: ${{ github.actor }} is testing

on: [push]

jobs:

  # This workflow only has the unit tests
  run-defined-unit-tests:

    # Type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./data-afternoon

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js Server
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install && npm i jest-environment-jsdom && npm install jquery && npm install coverage

      - name: Run tests and get Coverage
        run: npm run test
